### ISSUE TITLE
PathOfExileSteam crash on resolution change

### ISSUE THREAD

**Issue by JellyJones** [PeterTh/gedosato#132]
Tried all combination of compatibility options with no success.

Also crashes on alt-tab if I'm not using forced borderless.

LogLevel 1 [Output](https://dl.dropbox.com/s/m6pms3cpg2iva6l/PathOfExileSteam_Fri_Sep_12_19-00-46_2014.log)

If I set the LogLevel any higher I get [this](https://dl.dropbox.com/s/yqsk885v48n7tn0/crash.png) error and crash before the game even loads. [log](https://dl.dropbox.com/s/xnif8wjnusqgkkn/PathOfExileSteam_Fri_Sep_12_19-00-09_2014.log)

**Comment by Sacamano** [comment]
I am getting a crash on resolution change with gedosato running as well. Was a fix found for this yet?
