### ISSUE TITLE
FF13 | Works properly only in a small box in the top left of the screen

### ISSUE THREAD

**Issue by reinou** [PeterTh/gedosato#160]
There’s a small box (size depends on what resolution I downsample from, higher means smaller box) in the top left corner of the screen where it works correctly, but it’s kind of blurry outside of it. The menus and loading screens also only show in that box.

http://imgur.com/zMB1CwG
http://imgur.com/ehTC4bh
http://imgur.com/HWS0z0E

4670k @4.2GHz
AMD 280X @ Stock
8 GB ram
Win 7 64bit

EDIT: I've seen some other people with AMD cards having this issue, so it might have something to do with that.

**Comment by thekryz** [comment]
Sorry, but it's not fixed for me. Win10 1803/i5 3570K/770GTX
[This](https://steamcommunity.com/app/292120/discussions/0/152393186496044161/) seems to be a workaround.
