### ISSUE TITLE
GeDoSaTo breaking GPU clock speeds?

### ISSUE THREAD

**Issue by DAOWAce** [PeterTh/gedosato#275]
Test setup: Windows 7 x64, GTX 780, last few recent drivers.
Game: Might & Magic X downsampling from 2560x1440 to 1920x1080, all other options disabled.

Alt tabbing out of the game (fullscreen) and back in crashes the game with GeDoSaTo active.

After the crash, it seems my max clock speeds are limited to 540MHz. As a result, every single game I try to play afterward suffers heavily.  I've not found anything that resolves this issue aside from restarting the system.  *I discovered that enabling 'K-Boost' via EVGA Precision gets around it by forcing boost clocks all the time.. but it's not a viable solution.*

I can start/exit the game/gedosato numerous times without the issue appearing so long as it's clean.  It seems to only be after a crash that it breaks the clock speeds.

Very, very odd issue.  May be specific to this game as the way the engine has been programmed to run with it is quite frankly very very poor.  Unity is better than that, I know for sure.

I'll see if I can try playing around and crashing other games to see if the same issue happens with them, but this might take quite a while.  PITA to have to reboot my system every time.

**Comment by defontainedamien** [comment]
as i was feeling months ago i think gedosato dev is more or less abandonned... on his blog, the author was posting some list of previous projects he abandonned, i am sad of it and in the same time i understand that sometime you have to choose between things... i get a radeon 7950 and gedosato is still the only option to downsample (i can ds wwith enb in somegame but the feature is very gpu and cpu bottlenecking), sadly i think no future real evolution can be expected if someone get some news, please make us informed, the good news is that gedosato is open source software so anyone with good knowledge in prog. can continue the support of  ds tool...  I'm still hoping for dx11 support, my fatalist side says to me i'm the one who want these feature but sadly i'm a bad programmer even if i understand lots of concept i'm a f***** crappy coder... just one question: you get a 780 and i think you can downsample with the nvidia drivers, with a sweet fx profile  you get 99 per cent of what gedosato do at a minus cost why are you using gedosato? nota: i'm french so please excuse my ugly english, i try to write without using a traductor, i hope i ll be understood.

**Comment by DAOWAce** [comment]
Multiple reasons.

GeDoSaTo is an all in one program with downsampling, SMAA/FXAA and SweetFX all built in; fully compatible with overlay programs that inject in the game's render path; like Xfire.  If I use any of those programs by themselves, they conflict with eachother (granted SweetFX has built in SMAA too) and I cannot use other programs' overlays.  The same is true for ENB.

NVIDIA's DSR, while it works in DX11, uses preset multipliers for your primary monitor.  My primary monitor is a 21:9 display.  Numerous games are still incompatible with the 21:9 aspect ratio and as such I cannot downsample them with DSR.  It's also vastly simpler than GeDoSaTo and your only other option is an arbitrary 'smoothness' slider.

I also don't really use post-process features unless the game is just that drab looking; at that point I'd rather just use an ENB (though I still rarely do, only used for Skyrim).

While I wish GeDoSaTo was more developed and also added QoL features (like being able to disable the damn balloon popup every time it minimizes), it's still in a great state and is invaluable for increasing the image quality of games without real AA support (whether ingame or driver forced).  And in my case, for people with non-standard monitor setups, it's our only real option.

Also, I still used Vista up until a month ago (preparing to switch to X99, Intel stopped supporting Vista in 2013 for some ungodly reason), NVIDIA's DSR does not work on Vista, among numerous other things.

**Comment by defontainedamien** [comment]
well i better understand the reasons you still using gedosato instead of dsr, and as i also use enb in skyrim, as rarely as you for skyrim (some new mods are very awesome, for example tamriel reloaded hd and for a dx9 title it looks great with the good enb preset, for me it's realvision) , but man vista is so bwark (don't find any other word to describe this joke), how did you use it as far as one month ago, windows is make to be good only  twice releases, xp, seven and i hope it 10 are the only serious versions of the system... i think it's about license you've paid or something i cannot imagine it was your heart choice. i agree with you in game with no aa support gedosato is a great alternative, months ago i' ve tested gedosato+ enb in skyrim and it was great but my single 7950 was not able to run it smoothly even with 1440p so i choose enb in skyrim+ negative lod bias and it renders as good as uhd in 1600*900  with a crappy monitor (1366*768 fake 1080p) with other games i've tested gedosato many times but i don't really find a game that really need it in my collection so only borderlands2 looks awesome with it, but still good in only 1080p for example, witcher 2 get ubersampling, and other games as batman arkam origin don't need downsampling and are better looking in dx11 mode...but if one day there is a support for dx11 i'll take because downsample+ modern fx is really awesome...

**Comment by DAOWAce** [comment]
Vista is nowhere near as bad as all the FUD you've heard spread over all these years.

Everything people hated was due to Vista being a departure from the old way Windows worked.  Windows 95, 98, 2000 and XP were roughly all the same; XP being the biggest departure. Vista overhauled a lot, yet it also kept classic features people were familiar with from XP, which XP kept from 98.

7 removed all those classic features; everything I used on a daily basis.  8 overhauled the UI so much it was barely even familiar.  10 isn't changing much from 8, and DX12 is going to be exclusive to it (or so we believe), so we'll be forced into it eventually, just as I'm being forced into 7.

Every OS beyond Vista is rubbish as far as I'm concerned.  7 is the most similar to Vista (and with my UI mod, Classic Shell and 7+ Taskbar Tweaker it's usable on a daily basis), but it is by no means as usable as Vista is to me.

Yes, in beta and a bit before SP1, Vista wasn't flawless and had performance degradation; but through updates it was comparative to XP and became a damn fine OS. Hell, it even got DX11 support.  Now, compared to 7, there is virtually no difference in performance between the OS's.  The only thing 7 does better is native media handling.  The native UI rendering is worse for god's sake.

But no, that didn't matter; the mass market was full of ignorance and forced Microsoft to completely abandon it and release a slightly updated Vista with a new UI skin and call it Windows 7.  Everyone who was actually informed and liked Vista was left out in the cold.

I've ranted about this many places, and this ticket isn't the place to do so.

**Comment by PeterTh** [comment]
The real problem here is the crash, which is probably putting the driver in some weird state. GeDoSaTo doesn't really do anything with GPU clock speeds, so it also can't affect clock settings directly.

**Comment by karasuhebi** [comment]
@PeterTh is right, the issue is the driver crash; it has nothing to do with GeDoSaTo. It happens to me whenever I'm trying out an OC and the stress test causes a driver crash. The GPU won't hold a steady frequency after the crash, I always have to restart.

**Comment by DAOWAce** [comment]
I can't say I ever noticed it before it happened with this game.  I was also using Vista up until last month or so, which actually doesn't suffer numerous problems 7 does, though also has its own issues too.

Getting games to crash is pretty hard, usually only happens when you don't want it to.  GeDoSaTo makes some games crash very easily (just on a simple alt+tab), but that doesn't help trying to test this breakage without it.

I guess you can close this then, unless you want to change it to "GeDoSaTo crashing MMXL on alt+tab", though as a niche and buggy single player game, I doubt any troubleshooting efforts will be put towards it.

**Comment by karasuhebi** [comment]
@DAOWAce, if you wanna test the driver crash behavior, may I suggest overclocking your GPU to unstable clock speeds and then running something like FurMark?

**Comment by DAOWAce** [comment]
^ Funnily enough, I discovered I can pass benchmarks at +350Hz on the core. Ended up having the driver spam crash once I clocked up to +400MHz.

Though, the driver crash didn't lock the clock speeds.

Updating now after all this time as I discovered my games dropping frames hard; core clock speed was locked at 574MHz.  Haven't run GeDoSaTo, so something broke it.. yet I don't remember a game crashing.

NVIDIA should really do a bug bash update of their drivers.  Stop with the stupid geforce experience, stop with 3D and shadowplay; just bugfix the core drivers for a whole release cycle.  Sorely needed, especially considering they've had some known issues with certain games for **years**.

Anyway, closing issue; now confirmed it's not GeDoSaTo related.

**Comment by karasuhebi** [comment]
Glad to hear you were able to push your GPU further. Free performance is always good. :D

Check and see if your clock speed is locked at 574MHz when you have a browser tab open on YouTube or something along those lines. Close out your browser before gaming to be sure it's not that. I had an issue with my HD 7950 that made it so if you had any kind of hardware-accelerated tab opened it would look the GPU clock speed at 850MHz. Apparently this is a well-known issue/behavior on a lot of cards? Worth a shot.

**Comment by defontainedamien** [comment]
for me vsr hack with a custom tool resolve my need of downsampling in dx11.
Gedosato is for me useless but i hope dev will continue and break actual
dx9 limitations.

2015-05-06 18:22 GMT+02:00 Jaime J. Denizard <notifications@github.com>:
