### ISSUE TITLE
Setting hideMouseCursor to true causes FFXIII to crash when pressing Esc

### ISSUE THREAD

**Issue by karasuhebi** [PeterTh/gedosato#278]
If you set hideMouseCursor to true, Final Fantasy XIII will crash when you press Esc to close out of the game. This is 100% repeatable.

Windows 8.1 Pro x64
i5-4670K
HD 7950 w/Boost
GeDoSaTo 0.16.1759
Running the latest version for FF13 updated in December.

**Comment by karasuhebi** [comment]
Has anyone been able to recreate this issue?

**Comment by PeterTh** [comment]
I reproduced it. Very interesting bug.

**Comment by karasuhebi** [comment]
Ah, good to know. I thought maybe the issue was my computer. Thanks for the confirmation. :)

**Comment by PeterTh** [comment]
Fixed.

**Comment by karasuhebi** [comment]
Wow that was quick. Thank you! Yay!

**Comment by karasuhebi** [comment]
Looks like hiding of the mouse cursor is not working on FFXIII now. :-\
