### ISSUE TITLE
Downsampling from >4K resolutions in FFXIII causes 2-level downsampling and results in visuals that are less sharp

### ISSUE THREAD

**Issue by karasuhebi** [PeterTh/gedosato#281]
If you go into your FFXIII GeDoSaTo.ini and set your renderResolution to anything higher than 4K (2160p), and also set that res in the FFXIII launcher, it'll result in blurrier visuals when compared to 4K downsampling. I've noticed that when I set these higher resolutions, GeDoSaTo reports in the initial status message that it's downsampling twice: Once from the higher res to 4K and then a second time from 4K to my monitor's native 1080p. Why is it not going from the res I want to downscale to straight into 1080p? Could this be the cause of the less sharp visuals?

**Comment by PeterTh** [comment]
This is intended behaviour (without multi-level downsampling scaling from > 4x the resolution makes little sense), if you want sharper visuals you should use a different downsampling filter and/or resolution ratio.

**Comment by karasuhebi** [comment]
I try switching from bilinear to lanczos but it's still downsampling twice if I choose somethign that's >4K and it still looks less sharp than when I downsample to 4K. Any thoughts? I can provide screenshots and logs if that helps.

**Comment by karasuhebi** [comment]
bump

**Comment by karasuhebi** [comment]
Are you sure [this](https://github.com/PeterTh/gedosato/issues/281#issuecomment-90631073) is intended behavior?

**Comment by karasuhebi** [comment]
@PeterTh here's some screenshots so you can see what I'm talking about:
4K -> 1080p - http://i.imgur.com/VPx5BCW.png
5K -> 4K -> 1080p - http://i.imgur.com/SdVopDT.png
