### ISSUE TITLE
Right-click menu for GeDoSaTo tray icon

### ISSUE THREAD

**Issue by karasuhebi** [PeterTh/gedosato#286]
It would be great if you could implement a right-click menu to the system tray icon that had the option to Exit out of GeDoSaTo so one doesn't have to double click the icon and then close out of the program.

I'd also like an option to turn off the balloon tooltip from appearing every time one minimizes GeDoSaTo.

Thanks and keep up the great work!

**Comment by PeterTh** [comment]
This should be on the [GeDoSaToTool Repo](https://github.com/PeterTh/GeDoSaToTool). It's done in https://github.com/PeterTh/GeDoSaToTool/commit/afa9eccbf002c7689dacf83701cbd1e3ff932a2c.

**Comment by karasuhebi** [comment]
It doesn't seem to be working for me. :-\

Want me to make a separate issue for it or can we discuss here?

**Comment by karasuhebi** [comment]
@PeterTh: I tried building it myself from the source over at the GeDoSaToTool repo but VS 2013 is giving me some errors. Looks like the solution file is referencing two other project file in different directores. GeDoSaToTexM.csproj and GeDoSaToUpdater.csproj. Not entirely sure what's going on here.

C:\Users\Jaime\Documents\GitHub\GeDoSaToTexM\GeDoSaToTexM.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\Jaime\Documents\GitHub\GeDoSaToTexM\GeDoSaToTexM.csproj'.  C:\Users\Jaime\Documents\GitHub\GeDoSaToTexM\GeDoSaToTexM.csproj

C:\Users\Jaime\Documents\GitHub\GeDoSaToUpdater\GeDoSaToUpdater.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\Jaime\Documents\GitHub\GeDoSaToUpdater\GeDoSaToUpdater.csproj'.  C:\Users\Jaime\Documents\GitHub\GeDoSaToUpdater\GeDoSaToUpdater.csproj

**Comment by karasuhebi** [comment]
With the latest FPS limiter update, GeDoSaToTool updated. Everything is working as expected. Thanks again! :D
