### ISSUE TITLE
NET Framework Error Message During Update and start!

### ISSUE THREAD

**Issue by elajits** [PeterTh/gedosato#288]
I updated Gedosato Today and i keep getting a message when i start Gedosato and try to update it Microsoft Net framework 

System.InvalidCastException: Det gick inte att omvandla ett objekt av typen System.Boolean till typen System.String.
   vid GeDoSaToTool.MainForm.MainForm_Load(Object sender, EventArgs e)
   vid System.Windows.Forms.Form.OnLoad(EventArgs e)
   vid System.Windows.Forms.Form.OnCreateControl()
   vid System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   vid System.Windows.Forms.Control.CreateControl()
   vid System.Windows.Forms.Control.WmShowWindow(Message& m)
   vid System.Windows.Forms.Control.WndProc(Message& m)
   vid System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   vid System.Windows.Forms.ContainerControl.WndProc(Message& m)
   vid System.Windows.Forms.Form.WmShowWindow(Message& m)
   vid System.Windows.Forms.Form.WndProc(Message& m)
   vid GeDoSaToTool.MainForm.WndProc(Message& m)
   vid System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   vid System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   vid System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Inlästa sammansättningar **************
mscorlib
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
GeDoSaToTool
    Sammansättningsversion: 1.0.0.0
    Win32-version: 1.0.0.0
    CodeBase: file:///C:/GeDoSaTo/GeDoSaToTool.exe
----------------------------------------
System.Windows.Forms
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34239 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT-felsökning **************
För att aktivera JIT-felsökning (just-in-time ) måste .config-filen för det här
tillämpningsprogrammet eller datorn (machine.config) ha 
jitDebugging-värdet angivet i avsnittet system.windows.forms.
Tillämpningsprogrammet måste också vara kompilerat med felsökning
aktiverat.

Till exempel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

**Comment by PeterTh** [comment]
Fixed in https://github.com/PeterTh/gedosato/commit/dbc13d4435b95e9b47b04267e84238d0cf84abab
