### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by evilbananas** [PeterTh/gedosato#300]
EDIT: Once I ran Dark Souls II for the first time, it appears to be working to some degree.  I'm now only getting Error: Could not register global hotkey.

Getting the following on Windows 10:

Error loading GeDoSaTo.dll: Object reference not set to an instance of an object.
Activation failed: Invalid hook procedure
Error: Could not register global hotkey.

I've done the following:
- Run as administrator.
- .NET Framework 4.5 and Visual Studio 2013 redistributable packages installed
- Tried compatibility mode for Windows 8 with no luck

**Comment by Aphyxia** [comment]
Could you share how you got it to partially work? I'm having the same problem for Windows 10. Since I can't activate the program, running games doesn't really make a difference.

**Comment by evilbananas** [comment]
I ran Dark Souls II with GeDoSaTo closed; it was the first time I ran the game after installing it.  It installed some distribution packages at the beginning (like most games do) and then loaded the game.

I exited and opened GeDoSaTo again, it now allowed me to activate it.

I'm guessing the packages that were installed at the beginning  is what fixed the issue.

**Comment by Aphyxia** [comment]
Ah, it did indeed fix it. I guess some requirement is missing from the list.

**Comment by mitchray** [comment]
+1 this error is now present for me on Windows 10 (clean install).

I have tried running as admin and compatibility mode for Windows 7/8.

I don't have Dark Souls II to see which of its packaged installers apparently fixes this.

In addition to what comes with Win10 (like .NET Framework 4.6) I also have:
* Visual C++ 2008 x86
* Visual C++ 2010 x86
* Visual C++ 2012 x64
* Visual C++ 2013 x86
* Visual C++ 2013 x64
* .NET Framework 3.5

**Comment by LeafSenpai** [comment]
I just wanted to add, to get it to work you need to install the Directx 9 Libraries (DirectX End-User Runtimes (June 2010) ) http://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by Fooughhy** [comment]
There are quite a few files from June 2010. Which one, specifically, should be installed?
I guessed the d3dx9 one, but I still have the "Could not register global hotkey" error.

**Comment by LeafSenpai** [comment]
once you extract the file that I linked, running the installer will do it all o.O

**Comment by Fooughhy** [comment]
Wow... Didn't see that one XD Thanks!

**Comment by barros13** [comment]
I have the problem here and cant activate

Error loading GeDoSaTo.dll: Object reference not set to an instance of an object.
Activation failed: Invalid hook procedure
Error: Could not register global hotkey.

**Comment by PeterTh** [comment]
I think the only real issue related to Win10 here is the global hotkey. Everything else seem to be separate problems. I'll open a new issue for that.
