### ISSUE TITLE
Dark souls 2 no ds2 folder

### ISSUE THREAD

**Issue by officialstargator** [PeterTh/gedosato#305]
Hello! I have downloaded GeDoSaTo and installed it. I have put Texture dumping and Texture override to "true". But when i start up ds2 and equip a few diffrent weapons then close the game, there is no DarkSoulsll folder in the textures folder, located under: C:\GeDoSaTo\textures. How can i fix this?

**Comment by karasuhebi** [comment]
Are you using Dark Souls II: Scholar of the First Sin? That game uses a newer version of DirectX that GeDoSaTo is not compatible with yet.

If you're using the original Dark Souls II, did you change those settings in the game-specific profile? Does GeDoSaTo have write access to that folder?

**Comment by officialstargator** [comment]
oh that explains it! yes i am using Dark Sousll: scholar of the first sin. Thank you very much! :D. By the way do you know when it will be compatible?

**Comment by karasuhebi** [comment]
No problem. Glad I could clear that up. Don't forget to close this Issue! And sorry no, I don't know when (or if) there will be a version that will be compatible with DirectX 11. Keep an eye on the blog though, he will announce it there if and when it happens:
http://blog.metaclassofnil.com/
