### ISSUE TITLE
Legend of Grimrock 2, unable to downsample.

### ISSUE THREAD

**Issue by Fooughhy** [PeterTh/gedosato#306]
Hi!

Ok, so I am trying to downsample Legend of Grimrock 2 from 1440p to 1080p. I simple changed the "grimrock2" GDST file to have the option "renderResolution 2560x1440@60". 

The game start like normal, but in the uppder left corner the GeDoSaTo text says 1920x1080 -> 1920x1080 and the game doesn't seem to be downscaling. 

Why is this happening?

**Comment by PeterTh** [comment]
You need to actually select the resolution in-game.
