### ISSUE TITLE
Global hotkey registration fails on Win10

### ISSUE THREAD

**Issue by PeterTh** [PeterTh/gedosato#310]
Either investigate or just remove the feature. It was neat when I was debugging horrible problems in hooking at the beginning, but does anyone even use it now?

**Comment by karasuhebi** [comment]
I'd vote for keeping it. I don't use it too often personally but it's nice for troubleshooting or for quickly turning off GeDoSaTo before opening a program that has issues with it.

**Comment by PeterTh** [comment]
I've changed it to work on Windows 10.
