### ISSUE TITLE
Unable to hook on Deus Ex: Human Revolution DC with 'Chaos Flare'

### ISSUE THREAD

**Issue by cgerlach41** [PeterTh/gedosato#313]
Although 'Chaos Flare' seems to work very well overall, one game that does not work for me anymore, but has with older versions, is Deus Ex: Human Revolution DC. I suspect it might have something to do with that strange launcher the game uses, which is not a separate binary, like in other games. With the old version, the downsampled resolutions would also not show up in the launcher, but could be selected in the game itself, once it had launched (although changing it in game caused the game to 'hang'). The tool would however hook without problems in DX9 mode and i could set the resolution via the game config in the registry, which worked without problems.

With 'Chaos Flare' however the resolution does not get recognized on start and i end up in the launcher which resets all graphics settings every time.

What i did:
- verified that the game runs in DX9 mode
- tried all the config options which are labeled as 'might be required for some games to work'

**Comment by PeterTh** [comment]
I expected a lot more of this type of issue with the new hooking, I'm actually happy it seems quite limited so far.

I'll have to think about a viable path for covering these "special" games.

**Comment by PeterTh** [comment]
Just to make sure, other games work for you, right? 
(I want to eliminate the possibility of this being related to the other injection issue)

**Comment by cgerlach41** [comment]
Yes, all other games i tested so far work fine.

**Comment by SwinglesMan** [comment]
Same here with this game for me.

**Comment by PeterTh** [comment]
I'm closing this, since 3 major reasons for incompatibilities with the new version were identified and fixed/mitigated. If you still experience injection problems, create a new issue for them.

**Comment by cgerlach41** [comment]
I can confirm that the game now hooks fine with version 0.19.1987. This tool is getting better and better. I really appreciate the effort you put into this.
