### ISSUE TITLE
GeDoSaTo 0.19 “Chaos Flare” game speed increase!

### ISSUE THREAD

**Issue by JoseSnake** [PeterTh/gedosato#314]
While using the latest version of GeDoSaTo, "Kingdoms of Amalur: Reckoning™" runs Ultra Fast, like it's under speed hack.

This has been confirmed to happen with other games, namely "Dead Space 1", and it's not hardware/software specific, it happens in both Windows 7/10 and Intel/AMD/NVidia builds.

Using this version, fixes the problem so far: https://github.com/PeterTh/gedosato/tree/cae55cebc37b403da5381053a8ada8551111dc90

**Comment by SnowRay** [comment]
Hmm, apparently I have same problem, with F.E.A.R. 2.

**Comment by PeterTh** [comment]
Intersting! Must be related to some of the new time-related injection, though those should all be noops. I'll investigate when I get time.

Please post more examples of games for which this happens here if it does happen.

**Comment by slx7R4GDZM** [comment]
The new Steam version of Quake Live also does this if you use it with GeDoSaTo. Not sure if it really counts though because I think it uses OpenGL.

**Comment by Tachyoin** [comment]
Hyperdimenson Neptuna Re;Birth 1-3 also speeds up,

**Comment by PeterTh** [comment]
Neat, I actually own those and can test them.

**Comment by JoseSnake** [comment]
Sorry, I was away on work, hope you can fix the problem.

Hyperdimension Neptunia Re;Birth1 crashes on start for me, if I try to use GeDoSaTo. But it doesn't matter, unless someone else has this problem, don't bother with it.

**Comment by PeterTh** [comment]
Ok, this one was really quite obvious:
https://github.com/PeterTh/gedosato/blob/731e1f446f85e9f0ca14cd7bc16d335af27ed1ad/source/detouring.cpp#L681
(commited some testing code by accident)

Will be fixed this weekend.

**Comment by PeterTh** [comment]
Should be fixed by https://github.com/PeterTh/gedosato/commit/c5dbffa70ac5b62becb7c248f91a20a4eccc5941.
(And you can now do it on purpose if you want to)
