### ISSUE TITLE
Hiding HUD Help wanted

### ISSUE THREAD

**Issue by iRascaL** [PeterTh/gedosato#318]
Hi, 

So I've followed this guide to learn how to hide HUD's " http://www.pcgamer.com/how-to-create-sweetfx-style-shaders-that-dont-affect-the-hud-with-durantes-gedosato/ " 

I have found the hash and set up a profile for "Sniper Ghost Warrior 2" but once in game when I go to disable the HUD it says "HUD render disabled" but the HUD is still there and I also cannot take any HUDless screenshots :/ I was just wondering if maybe there was a more up to date guide or if anyone could help me out? Many thanks :)

**Comment by PeterTh** [comment]
From your description, it sounds like you didn't find the correct hash. I'm closing this since it's not really an issue, but if anyone has any tips specific to this game feel free to post them below.

**Comment by iRascaL** [comment]
Okay thanks for replying, I will look at others hash's later. Sorry about posting in issues I didn't really know where is to post is there a forum or something I can use next time?
