### ISSUE TITLE
Gedosato Problem List

### ISSUE THREAD

**Issue by SwinglesMan** [PeterTh/gedosato#319]
0.19.1987

Haven't tried the override method, but there are games on the list that add rezzes with DSR, but still doesn't with Gedo. Those ones don't count to use the override method because it should add the rezzes like DSR. If a game works that needs the override method, just ignore them in the list then for I haven't tried the override methods.

All games that say directx 9.0c on steam page mostly:

Deus Ex Human Revolution DC = black screen when trying to use 4096x2304 and up
Deus Ex - The Fall = Works
Dynasty Warriors 8 - Empires = No new rezzes added/no gedo loaded bar
Dynasty Warriors 8 - Xtreme Legends = No new rezzes added/no gedo loaded bar
MDK 2 = No gedo loaded bar/new rezzes reset upon re-entering
MGR-R = No new rezzes added/no gedo loaded bar
Mirror's Edge = Injects 4K rezzes, but they are actually low rezzes and not 4K at all
Republique Remastered = Crashes
Samurai Warriors 4-II = No new rezzes added/no gedo loaded bar
Spiderman Web of Shadows = No new rezzes added/no gedo loaded bar
Legend of Korra = No new rezzes added/no gedo loaded bar
Bionic Commando = Seems to work with 4K. Still have jaggies makes it questionable. Lowres shadow.
Blood Rayne Betrayal = No new rezzes added/no gedo loaded bar
DuckTales = Injects 4K rezzes, but has jaggies so it being true is questionable
Ghostbusters = Injects 4K rezzes, but has jaggies so it being true is questionable. Highlight haze effect on menu gets bad.
Hydrophobia Prophecy = No new rezzes added/no gedo loaded bar
Life is Strange = Works
Pirate Warriors 3 = No new rezzes added/no gedo loaded bar
Remember Me = Works
Toren = Crash
Tokiden - Kiwami = No new rezzes added/no gedo loaded bar
Way of the Samurai 4 = Works, low res shadows, rez capped at 4096x2304
Sexy Beach - Premium Resort = No new rezzes added/no gedo loaded bar
Leasure Suit Larry - Magna Cum Laude = No new rezzes added/no gedo loaded bar
DoA5 = No new rezzes added/no gedo loaded bar
Injustice = Works
Kings of Kung Fu = Crashes
Martial Arts Capoeira = Unknown, no resolution settings anywhere
Naruto UNSR = No new rezzes added/no gedo loaded bar
Naruto UNS 3 FB = No new rezzes added/no gedo loaded bar
All Street Fighter IV type games = No longer working
RE ORC = No longer working
RE Rev = Not working
RE Rev 2 = Rez capped at 3840x2160
RE 1 Remaster = Doesn't work
RE5 Gold Edition = Doesn't work
RE6 = No longer works
State of Decay Vanilla = No new rezzes added/no gedo loaded bar
TellTale Walking Dead games = No new rezzes added/no gedo loaded bar
Contrast = Not working
Kickbeat = Not working
Qube DC = Not working
Distance = No longer works
Need for Speed Carbon = No new rezzes added/no gedo loaded bar
Need for Speed Most Wanted = No new rezzes added/no gedo loaded bar
Need for Speed The Run =  No new rezzes added/no gedo loaded bar
Need for Speed Undercover = No new rezzes added/no gedo loaded bar
Nitronic Rush = Works
Final Fantasy XIII = Rez gets injected; not really the injected rez (actually a lower rez)
FFXIII-2 = No longer working
Tales of Zestiria = Doesn't Start
Jet Set Radio = Works

Start with Windows = NOT WORKING
Save Previous Settings on Update = NO OPTION

**Comment by slx7R4GDZM** [comment]
>Mirror's Edge = Injects 4K rezzes, but they are actually low rezzes and not 4K at all

Are you sure? It works fine for me, pic related.
![screenshot_2015-11-08_19-17-10_1](https://cloud.githubusercontent.com/assets/8537148/11025254/c399b85c-864d-11e5-97ab-d493d50f1784.jpg)

**Comment by PeterTh** [comment]
This is too much stuff in one report, especially since some of it is 
* already covered in other issues, e.g. starting with windows problems
* based on a misunderstanding of how GeDoSaTo works, like saving settings (that's what user settings are for)
* games which inherently don't support higher resolutions (Dynasty Warriors, MGR, Toukiden, Pirate Warriors 3 ...)
* games which work perfectly as long as you use documented in-game settings (e.g. Zestiria)

Some of them might actually be GeDoSaTo issues, but you should make separate issues for those and not a list which throws together various non-issues with legitimate problems.

**Comment by SwinglesMan** [comment]
Ignore everything. Yeah, that's good...


  **  already covered in other issues, e.g. starting with windows problems**
Okay, so when you gonna fix it? It's been years since it was first reported. In order to gloat about fixing company games, your own fix should work properly :P
    
"based on a misunderstanding of how GeDoSaTo works, like saving settings (that's what user settings are for, and these are saved across updates)"
How do you even use user settings? Where is it at? every update, it reverts EVERYTHING back to default and I constantly have to redo everything over and over. Your documentation is very poor. Nevermind, had to read commented out stuff at the top of gedo settings. If it were in the readme like it's supposed to be.... 

    "games which inherently don't support higher resolutions (Dynasty Warriors, MGR, Toukiden, Pirate Warriors 3 ...)"
And how would I have known this? Magic? I can't look at every secret hidden game section on the internet. 

    "games which work perfectly as long as you use documented in-game settings (e.g. Zestiria)"
Just searched readme and update files that come with gedosato. Don't see ANYTHING that supports you saying that it's documented. You don't talk about every single game on the website. How would I know to magically look for how to get a game to work?


And what do you have to say about restoring the FFXIII fix to fix the missing texts? I've asked constantly for a year off and on now but you ignore and yet talk about my problems being illegitimate....
