### ISSUE TITLE
RequireSignedAppInit_DLLs prevents GeDoSaTo injection

### ISSUE THREAD

**Issue by bVork** [PeterTh/gedosato#320]
The new version ("Chaos Flare", 0.19.1987), installed cleanly, continues to not function for me. I have copy and pasted my report from issue #316:

Operating System: Windows 7 64-bit, English but running in Japanese locale
Install directory: C:\GeDoSaTo
Hardware description: i7 4790k, 16gb ram, Radeon R9 290 (4gb) using Catalyst 15.7 drivers
Any other injectors? RadeonPro, but exiting it and disabling the service changes nothing.
Antivirus: Avast. Again, I tried disabling it and nothing changed.

Tested games:
Valkyria Chronicles - Runs but won't acknowledge the existence of resolutions beyond 1920x1080.
Dreamfall: The Longest Journey - Runs but won't acknowledge the existence of resolutions beyond 1920x1080.
Darksiders II (both original release and the new Deathinitive Edition) - Runs but won't acknowledge the existence of resolutions beyond 1920x1080.

The previous version ("Disharmonized Genesis", 0.18.1884) has no problems with all three of the above games.

**Comment by PeterTh** [comment]
Do any games actually work for you?
(I need to know if it's a general setup issue or a game-specific issue)

**Comment by PeterTh** [comment]
The above is because I thought for a second that Dreamfall is DX8, but I think it's 9 after all.

**Comment by PeterTh** [comment]
I just tried Valkyria, works perfectly for me.

**Comment by bVork** [comment]
The games run with the latest version of GeDoSaTo, they just don't actually let me select any resolutions beyond 1920x1080. This is a step back from the older version of GeDoSaTo, which lets me do proper downsampling. I guess I'm just going to keep using that version, I guess.

**Comment by PeterTh** [comment]
When I said that it works for me, I meant including downsampling. Again, are any games actually working for you with the latest version?

**Comment by bVork** [comment]
No. None of the games are working. That's why I created this issue. Downsampling is not possible for me on the latest version of GeDoSaTo.

**Comment by PeterTh** [comment]
So the specific games have nothing to do with it really, it's a general issue with the latest version on your system.

**Comment by PeterTh** [comment]
Since you're on Windows 7, it can't be the secure boot issue.
Can you search your registry for the "RequireSignedAppInit_DLLs" key and report its value, if any?

**Comment by bVork** [comment]
I found two instances of that key. One is in "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows" and the other is in Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Windows"

Both are REG_DWORDS with a value of 1.

**Comment by PeterTh** [comment]
Can you set it to 0 and try if that fixes your issues?

**Comment by bVork** [comment]
Yes, that solves it for Dreamfall and Valkyria Chronicles! Thanks a lot!

Darksiders II: Deathinitive Edition won't report higher resolutions, but I think that's caused by the recent beta patches to the game, since even the old version of GeDoSaTo that previously allowed me to downsample isn't working on it anymore.

**Comment by PeterTh** [comment]
Great, I'll have to fix this in future versions

**Comment by PeterTh** [comment]
Fixed in the update pushed today.

**Comment by 13xforever** [comment]
I don't see any signatures on the GeDo files, and I don't see any relevant commits either. Could you link a specific commit with the fix?

Also, it could've been enabled via domain policies (i.e. when you configure the corporate e-mail that requires certain policies to be applied before you can use it), so it's not prudent just silently disable these settings. You should warn and ask to instead, like with the secure boot.
