### ISSUE TITLE
C&C3 no longer works

### ISSUE THREAD

**Issue by slx7R4GDZM** [PeterTh/gedosato#321]
Command & Conquer 3: Tiberium Wars no longer injects at all in the new versions of GeDoSaTo. I think it might have something to do with how launching the game starts a file called cnc3game.dat rather than an exe but I'm not sure.

**Comment by PeterTh** [comment]
The actual executable process is called cnc3game.dat?
Because it certainly won't work then, but that should be rather easy to fix.

**Comment by slx7R4GDZM** [comment]
>The actual executable process is called cnc3game.dat?

That's what shows up in the task manager details. Steam launches CNC3.exe which appears to open up a file called cnc3game.dat.

**Comment by PeterTh** [comment]
I see. As I said, that should be easy to fix

**Comment by PeterTh** [comment]
Try this: https://github.com/PeterTh/gedosato/blob/master/pack/gedoshim.dll

**Comment by slx7R4GDZM** [comment]
Same nothing happens, no logfile or anything.

**Comment by PeterTh** [comment]
Hmm, that should have fixed it if it was because of the file ending.
Sadly, cnc3 is the one I don't have (I have RA3 and cnc4 on origin) so I can't test it.
