### ISSUE TITLE
`getSystemDllName (...)` makes poor choice of log text regarding DLL paths.

### ISSUE THREAD

**Issue by Kaldaien** [PeterTh/gedosato#330]
On line [733 of detouring.cpp]
(https://github.com/PeterTh/gedosato/blob/master/source/detouring.cpp#L733), we have:

    string getSystemDllName(const string& name) { 
      char sysdir[MAX_PATH]; 
      GetSystemDirectory(sysdir, MAX_PATH); 
      string fullPath = string(sysdir) + "\\" + name; 
      SDLOG(28, "Full dll path: %s\n", fullPath.c_str()); 
      return fullPath; 
    } 

This will always return the host's native DLL directory (e.g. 64-bit DLLs on a 64-bit system and 32-bit DLLs on a 32-bit system). If the software is 32-bit on a 64-bit operating system, this _"SystemDllName"_ seems rather not the "Full dll path" as the log claims - the DLL appropriate for the running architecture will be found in the Wow64 directory rather than the location listed.

You can open that file from a 32-bit piece of software and Windows is going to silently redirect everything to SysWow64. But this doesn't feel right. If you use that file name in a log, there's no way to distinguish it from the 64-bit version - that is NOT its fully-qualified name.

<hr>

Logically, I would expect to see something more like this:

    string getSystemDllName(const string& name) { 
      BOOL bWow64 = FALSE;
      IsWow64Process (GetCurrentProcess (), &bWow64);

      char sysdir[MAX_PATH];

      if (bWow64)
        GetSystemWow64Directory(sysdir, MAX_PATH);  // SysWOW64 (generally speaking)
      else
        GetSystemDirectory(sysdir, MAX_PATH);       // System32 (generally speaking)

      string fullPath = string(sysdir) + "\\" + name; 
      SDLOG(28, "Full dll path: %s\n", fullPath.c_str()); 
      return fullPath; 
    }

This properly handles the _very common_ case where a 32-bit piece of software is running on a 64-bit OS. If you are going to fully-qualify these DLLs, it would make sense to do so without relying on FS redirection.

**Comment by PeterTh** [comment]
Good point.

**Comment by PeterTh** [comment]
Fixed in the update pushed today.
