### ISSUE TITLE
csgo hlae crash

### ISSUE THREAD

**Issue by chiefscott** [PeterTh/gedosato#331]
Hi

I use another tool called HLAE ( http://www.advancedfx.org/ )  to create cinematics within CSGO.

HLAE needs to be launched so I can access my cam paths and I'd like to record at high resolutions with your program simultaneously.

Your program and HLAE don't play well together.

Is there anyway to manipulate how the injections work so they can play nice together? :)

Will donate for a solution!

**Comment by PeterTh** [comment]
Sorry, it's basically impossible to support the interaction of multiple third-party injection hacks. There's just too much which can go wrong. You can _try_ enabling the "interceptOnlySystemDlls" setting, but it's unlikely to help.
