### ISSUE TITLE
Psychonauts support

### ISSUE THREAD

**Issue by ribeena** [PeterTh/gedosato#332]
Hey There,
I've been able to use uMod, sweetfx and enbseries with Psychonauts (steam) but not with GeDoSaTo.

I don't get any error log, it just doesn't seem to recognise it. It could be a n00b problem, but i have tried changing the settings including;
emulateFlipBehaviour true
preventSteamOverlay true
loadD3DEarly true

Any tips or suggestions appreciated.
Alex

(Using windows 10, gedosato 0.20.2008 and have installed Visual Studio 2015 redistributable package)

**Comment by ribeena** [comment]
It was as a result of having a space in the folder install!

**Comment by v00d00m4n** [comment]
So space bug was not fixed after all. I suppose this bug was posted after my steam thread?

**Comment by ribeena** [comment]
I should have listed it as a duplicate as i found the solution to the bug in someone else's bug report. I can't seem to see what bug report it was now though - so might still be an issue.
I swapped to uMod as it didn't have that bug and easier for other people to use for texture swapping.



Date: Mon, 18 Jan 2016 05:10:48 -0800
