### ISSUE TITLE
Config_User Folder

### ISSUE THREAD

**Issue by shinra358** [PeterTh/gedosato#333]
Can you make it so there is a config_user folder so our game profiles wouldn't get overwritten with things from new updates and we can pick and choose what to bring over. It'll work similarly to the gedosato_userconfig inis.

**Comment by PeterTh** [comment]
you can have user profiles for each game, and they shouldn't be overwritten. Or are you talking about something else?

**Comment by shinra358** [comment]
What about instances when a new game comes out, and the users makes a profile for it, and later, an update comes out by you that adds a profile for that game which overwrites the users?

I would like a folder called Config_User which takes priority over the Config folder so that game profiles won't be overwritten. New updates by you can still go in the Config folder. What we want not to be changed by an update should go in the Config_User folder. That's what I mean.

**Comment by PeterTh** [comment]
if there is a new game released for which there is no profile yet then you should create one, keep it empty, and immediately create a user profile (using the "U" button) and store your settings there.

**Comment by shinra358** [comment]
Just updated and of course the final fantasy xiii settings I had reset. Good game -_-
All you gotta do is get rid of that useless backup feature and use this instead. It's quicker and smarter and doesnt require filling up folder with endless backups on every update. But noooooo. That's way to simple and easy. Smh.

**Comment by PeterTh** [comment]
Or you could use the tool as intended.

**Comment by shinra358** [comment]
Yeah, I'm sure constantly deleting folders and redoing everything every update is what is intended...

**Comment by PeterTh** [comment]
No. What's intended is, as I said above, **_to put your user settings in a user settings file_**. If that file gets overwritten or removed, that's a bug.

**Comment by shinra358** [comment]
I know about the gedosato_user.ini for main settings. I'm not talking about that.
I'm talking about config > 'insert game name here' > gedosato.ini

So are you saying that I should change that ini to gedosato_user.ini too?

**Comment by PeterTh** [comment]
I did mention how to do this further up:
> immediately create a user profile (using the "U" button) and store your settings there.

I only introduced the backup feature because people wouldn't use user profiles and kept complaining about losing settings :/
