### ISSUE TITLE
Lightning Returns shadow Artifacts build 0.20.2056

### ISSUE THREAD

**Issue by chrcoluk** [PeterTh/gedosato#334]
Hi

I updated gedosato and activated it.

When loading lightning returns I get weird shadow artifacts, one is almost permanent a big square shadow in the bottom right (including in battles), the others come and go, but they shadows stretched, in wrong place etc.

Screenshot here.

https://www.dropbox.com/s/jmhxje7sctj8ujf/2015-12-30_00005.jpg?dl=0

Config as follows.

Win7 64bit up to date.
Nvidia gtx 970 using 361.43 drivers
Intel 4670k cpu
Lightning Returns english version, updated with latest patch.
Graphics options all set to advanced, (still occurs when on standard anyway).
Game resolution 1440p no scaling.
No SGSSAA or other driver related AA overrides.
No downsampling in gedosato.
SMAA on AO on, postprocessing off.

Let me know if you need more info.

**Comment by PeterTh** [comment]
You need to set the in-game resolution to the same one set in the gedosato config file for Lightning Returns.

**Comment by thatfulvioguy** [comment]
I've been seeing this issue, but only when downscaling to 1080p from 2560x1440 (the same resolution that chrcoluk was playing at). The issue doesn't happen when downscaling from 4k nor when I'm running without downscaling at 1080p. I've adjusted the in-game resolution setting to match GeDoSaTo's in all cases.
