### ISSUE TITLE
Start Minimized

### ISSUE THREAD

**Issue by shinra358** [PeterTh/gedosato#343]
Needs a start minimized option. Autostart with windows still ain't working so forcing it to autostart through other means makes the program start maximized. Making a windows shortcut to force it to start minimized doesn't work.

**Comment by karasuhebi** [comment]
Would this Issue be applicable to PeterTh/gedosato or PeterTh/GeDoSaToTool? Seems more like a GeDoSaToTool Issue to me.

**Comment by shinra358** [comment]
btw, @PeterTh 

The way most companies get past this (the autostart with windows issue as mentioned in my previous 2nd sentence in the first post) is to tell the program to create it's own task scheduler event to bypass the uac when start with windows is activated. CCleaner, MSI Afterburner, etc. all do this. Of course a standard account wouldn't allow it to work, but you shouldn't play on a standard windows account anyway if you're a gamer. Causes many confilcts with alot of things.
