### ISSUE TITLE
ToS: Setting resolution to anything other than native 1920x1080

### ISSUE THREAD

**Issue by Ahammer18** [PeterTh/gedosato#346]
Setting the resolution to anything higher than my native 1920x1080 causes the game to be entirely rendered in a small rectangle in the top-left of the screen.

**Comment by PeterTh** [comment]
Do you have the in-game resolution setting at 720p and are you running the game in fullscreen?

**Comment by Ahammer18** [comment]
Game is in fullscreen, When I try to set the in-game resolution to match the one I set it crashes my game with the message 

TLGraphic/NewVortexBuffer

**Comment by Ahammer18** [comment]
Fuck, verified my game cash and reaquired a missing file, it works now.

Thanks for your time, GeDoSaTo is great.
