### ISSUE TITLE
[Enhancement] Replace SuperFastHash with xxHash

### ISSUE THREAD

**Issue by tapcio** [PeterTh/gedosato#347]
SuperFastHash has many collisions, xxHash is faster and have much less collision rate (ie. none in SMHasher test): https://github.com/Cyan4973/xxHash/blob/master/xxhash.h#L40

**Comment by PeterTh** [comment]
It would probably be better, but I can't really change the hashing now. That would break _all _existing hashes.

**Comment by tapcio** [comment]
Yes, but changing it later will break even more existing hashes. You can add option to select hashing mode to make transition smoother. SuperFastHash will cause problems, sooner or later ( http://programmers.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed ). Be warned :p
