### ISSUE TITLE
What requirements must be met to use AO/DOF/Bloom?

### ISSUE THREAD

**Issue by amackenzie** [PeterTh/gedosato#355]
I managed to find a good hash (40f6f57f, injectDelayAfterDraw true) to apply various effects before the UI is drawn in Blade & Soul, and the AA and postprocessing work like a charm.

However, I'm not sure how to get AO/DOF working, and Bloom gives an error saying that it doesn't work with this plugin (poking around, I'm guessing it's only for DS2?).

What conditions must be met for AO/DOF to work? Is it necessary to specify a depth buffer somehow? Or are they meant to be specific to certain games and not used as a general option?

Any information would be great. Thank you.

**Comment by PeterTh** [comment]
You need either a game-specific plugin which exposes a Z-buffer, or to use the generic depth plugin (which doesn't have perfect compatibility).  You use the generic depth plugin by specifying `
pluginOverride GenericDepthPlugin` in the user configuration file for a given game.
