### ISSUE TITLE
Final Fantasy XIII - Missing Texts in the DataLog, Equipment Menu

### ISSUE THREAD

**Issue by Fukuroul** [PeterTh/gedosato#374]
OS - Windows 10
Resolution 1920x1080
GeDoSaTo ver 0.21.2310
I has been using GeDoSato since April 2016. The game run perfectly through the launcher at 1920x1080. It worked very well. I updated to 0.21.2310 build this morning and found the problem mentioned above, missing texts in the DataLog when selecting chapters, in the small gear list window at the bottom left screen when changing gears, the texts look like it's erased. The problem don't occur when I start ffxiiiimg.exe directly. I found 
"~RSManagerDX11
Console DX11 delete" in recent logs but the logs created in April don't have it, I can provide them if you want

**Comment by Kibatodos** [comment]
This is my today log

> ===== Wed Jun 15 20:46:34 2016 =====
===== start GeDoSaTo version 0.21.2310 built on 2016/06/12 10:30:28 "How Could Hell Be Any Worse" (GENERIC/RELEASE) = fn: ffxiiiimg
===== installation directory: E:\Games\FF13 Tools\
~RSManagerDX11
Console DX11 delete
~RSManagerDX11
Console DX11 delete
~RSManagerDX11
Console DX11 delete
~RSManagerDX11
Console DX11 delete
~RSManagerDX11
Console DX11 delete
~RSManagerDX11
Console DX11 delete
~RSManagerDX11
Console DX11 delete
~RSManagerDX11
Console DX11 delete
hkIDirect3DSwapChain9::GetPresentParameters
hkIDirect3DSwapChain9::GetPresentParameters
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
Drawing console
hkIDirect3DSwapChain9::GetPresentParameters
===== end =

**Comment by ebugusey** [comment]
Set resolution to 1280x720 in launcher.

**Comment by ebugusey** [comment]
Well, gedosato now doesn't work with this game, because of #371, don't bother for now.

**Comment by shinra358** [comment]
Guy on steam fixed it and proposed to put it in newer versions buy durante just doesn't listen to anything:

v0.212132:
https://steamcommunity.com/app/292120/discussions/0/619573787403571892/?ctp=7

And ebugusey, what's the point in being a jackass? If ppl didn't want to utilize their machines, this wouldn't be desired in the first place. Nor would gedosato have been made...

I suggest to always stick to this version until an update comes out that actually features something that you want. Dont just update for the sake of it.

**Comment by ebugusey** [comment]
> durante just doesn't listen to anything

@shinra358 Learn how to use commit history before making statements like this, mate.
a9799b23145d25feee4cee1f3d877df12d3a0f2d

And this is open source project. The most useful way to contribute is making a pull request.
If you think someone doesn't listens or that a project should go another way, fork it and make it with your own blackjack and hookers.

**Comment by shinra358** [comment]
don't need to learn anything. if the solution is fixed, then why is it still open? How about using the close button properly. Not only that, the commit says jan 31st. Yet, a fix was made in March on the steam site..........  what does that tell ya?
So yeah, you learn logic.

**Comment by ebugusey** [comment]
@shinra358 You are an arrogant prick, but I will try to be polite with you and explain everything.

## How gedosato project release and updating works
When developer makes a commit it doesn't mean that project is in usable state or that you will get a release. 

Durante decided that builds should be included in repository (and I don't particularly agree with this decision, because github have release system that works for most buildable projects). So when he decides that it's time for release he includes his build in a commit. 

Release builds located [here](https://github.com/PeterTh/gedosato/tree/master/pack). 
His update program periodically checks for new build and download new releases from that location.

So, to answer your **second** question:
Commit a9799b23145d25feee4cee1f3d877df12d3a0f2d was made on **31 Jan** and incorporated into main repository on **4 Feb** with commit 69cc9719d45a612e95e05492c5566d12f2d74254. Judging by [history of main library that does stuff](https://github.com/PeterTh/gedosato/commits/master/pack/GeDoSaTo.dll) and [merge graph](https://github.com/PeterTh/gedosato/network), build with this change was made here abec452999f87848086998887895efe9a8cdf178 on **7 Jun**.

But not only that, you actually misremember things. Because user Jacuzzi actually [posted his build](https://steamcommunity.com/app/292120/discussions/0/619573787403571892/?ctp=4#c451852225143379773) the same day he committed his changes.

## Why it doesn't work in current release
Because of #371 nothing works like it should. As I already mentioned in my second comment.

## Why this issue isn't closed
Because @Kibatodos or repository owner haven't closed it. 
Why they haven't closed it? Well, this is interesting question. Possible answers are:
1. Because OP doesn't care. He posted it and don't plan to close it even after it's resolved. It happens all the fucking time. Just look at https://github.com/qbittorrent/qBittorrent
2. Because Durante doesn't care or don't have enough time to close obsolete issues. He is one man. With a job. Again, look at qBittorrent.
3. Because OP didn't see it fixed. You still remember that _nothing_ works like it should because of #371, right?

## Afterword
It's hard, but I'm trying to be polite with you.
So stop spewing shit and do your research before posting.

**Comment by Fukuroul** [comment]
I just saw the notification yesterday also haven't touched FFXIII for months. I don't have time to test it myself if it's fixed or not but the issue will be closed now.
