### ISSUE TITLE
Unable to install GeDoSaTo

### ISSUE THREAD

**Issue by ghost** [PeterTh/gedosato#415]
I am having an issue with GeDoSaToUpdater. Whenever I run it and give it a path to install in, it immediately comes up with an error. https://puu.sh/Bhwmv/5ebd17bf50.png
Details: https://pastebin.com/DHeuUHnf

I have all the requirements mentioned in the blog, including a Visual Studio 2017 package and NET Framework 4.5 (which my OS comes with anyway), and Secure Boot has been disabled.

**Comment by GodSponge** [comment]
Found another thread with some help. Doesn't fix the updater, but does allow you to get the program. https://github.com/PeterTh/gedosato/issues/411
