### ISSUE TITLE
Steam big picture mode freezes when Gedosato is active

### ISSUE THREAD

**Issue by v00d00m4n** [PeterTh/gedosato#42]
Despite all steam exes are added to blacklist and gedosato is set to white list mode for some reason it hooks steam and steam hangs right after login screen in Big Picture mode.

I combination of gedosato and steam both set to launch at windows start this combo i really disasterous.

I think gedosato should not even try to hook any process beyond those, listed in in whitelist, but for some reason it does.

**Comment by luisventura** [comment]
hi Peter! I just experienced this issue, but not in the same conditions.
Anyway I tested it a few times, with and without Gedosato.
For me, it hangs on the game executable, if Big Picture overlay is opened while in game (big picture by itself, works fine), and gedosato is active.
Tried with Dark Souls II, GeDoSaTo 0.16.1759 Third Ensemble.
