### ISSUE TITLE
Castlevania: Lords of Shadow - Ultimate Edition, Black Screen when downsampling

### ISSUE THREAD

**Issue by Aexrael** [PeterTh/gedosato#82]
I'm getting a black screen when downsampling Castlevania: Lords of Shadow - Ultimate Edition on Steam, though I can hear the sounds. The game was already whitelisted so I'm guessing someone got it to work at some point, but the config file is empty.

Screenshot taken with Steam, showing the GeDoSaTo info with downsampling disabled, http://imgur.com/a/btfGF#0

I can see the four downsampling resolutions available in the Video menu, but as soon as I select one and go back a page when the game initializes the resolution and swaps to the "Do you want to keep these settings" page, it goes dark. I can still navigate the game at this point, hear the sounds and such.

Cas: LoS - UE Video settings are Max/Yes/Max/x16/Yes, Fullscreen.

Unfortunately the logs are mostly empty.
===== Tue Aug 19 15:00:52 2014 =====
===== start GeDoSaTo version 0.12.1244 built on 2014/08/18 18:04:30 "Sepia Recollections" (GENERIC/RELEASE) = fn: castlevanialosue
===== installation directory: C:\Users\"Username"\Documents\GeDoSaTo\
===== end =

This is on an Nvidia GTX 770 with driver v340.52 on Win 8.1 with the latest updates and GeDoSaTo 0.12.1244, GedoSaTo settings are for the most part default, other than the renderResolutions.

My GPU driver settings are default, DirectX is the latest, only 1 monitor, not sure what else to think of at this point.

**Comment by raffaelepes** [comment]
RISOLTOOO SCHERMO BIANCO E NERO
1: scaricate questo pacchetto CASTLEVANIA LOS ENB
2:estraete l'archivio utilizzando 7z o winrar
3: copiate i file della cartella "BIN" nella directory C:programmi Castlevania Lords of Shadow - Ultimate Editionbin
o C:\programmi\steam\steamapps\common\castlevanialos\bin (questo dipende in quale directory avete installato il gioco)
4:eliminate il file dxgi.dll
5:avviate il gioco (con me ha funzionato)

mediafire.com/download/44iwcjj86m5onj5/Castlevania+LoS+ENB.7z
